cav:
	git add -A
	git commit -m "Updated files(s). - Cav"
	git push

get: 
	git add -A 
	git commit -m "Updated file(s). - Get"
	git push

mika:
	git add -A
	git commit -m "Updated file(s). - Mika"
	git push
